SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE `tb_ai_bot` MODIFY `alias` VARCHAR(255) DEFAULT NULL COMMENT '别名';

ALTER TABLE `tb_ai_workflow` MODIFY `alias` VARCHAR(255) DEFAULT NULL COMMENT '别名';

ALTER TABLE `tb_ai_knowledge` MODIFY `alias` VARCHAR(255) DEFAULT NULL COMMENT '别名';

ALTER TABLE `tb_ai_plugin` MODIFY `alias` VARCHAR(255) DEFAULT NULL COMMENT '别名';

SET FOREIGN_KEY_CHECKS = 1;